# Generated by Django 2.2.6 on 2019-10-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageText',
        ),
    ]
