# Generated by Django 2.2.6 on 2019-10-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_technologiesmoretext_technologiestext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technologies',
        ),
    ]
