# Generated by Django 2.2.6 on 2019-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191004_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='textEN',
            field=models.TextField(verbose_name='Дополнительный текст EN'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='textRU',
            field=models.TextField(verbose_name='Дополнительный текст RU'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='textUZ',
            field=models.TextField(verbose_name='Дополнительный текст UZ'),
        ),
    ]
