# Generated by Django 2.2.6 on 2019-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191005_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='textAddEN',
            field=models.TextField(default=None, verbose_name='Дополнительный текст EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologies',
            name='textAddRU',
            field=models.TextField(default=None, verbose_name='Дополнительный текст RU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologies',
            name='textAddUZ',
            field=models.TextField(default=None, verbose_name='Дополнительный текст UZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technologies',
            name='textEN',
            field=models.TextField(verbose_name='Описание EN'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='textRU',
            field=models.TextField(verbose_name='Описание RU'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='textUZ',
            field=models.TextField(verbose_name='Описание UZ'),
        ),
    ]
