# Generated by Django 2.2.6 on 2019-10-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191005_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnologiesMoreText',
        ),
    ]
